### ISSUE TITLE
Update code for Julia 0.7

### ISSUE THREAD

**Issue by oliviaAB** [alanderos91/BioSimulator.jl#13]
Hi,

I updated my version of Julia to Julia 0.7 and ran some simulations. I got some warnings about syntax changes in the newest version of Julia. Are you planning on updating the package to make it compatible with this newer version of Julia? If this can help, here is the list of changes required:
- `Base.randexp` is deprecated and has been moved to the standard library package `Random`. A `using Random` is required;
- `Base.rowvals`, `Base.spzeros`, `Base.nonzeros` and `Base.nzrange`  are deprecated and have been moved to the standard library package `SparseArrays`. A `using SparseArrays` is required;
- The syntax `Array{T}(m, n)` is deprecated; `Array{T}(undef, m, n)` must be used instead;
- `linspace(start, stop, length)` is deprecated, `range(start, stop = stop, length = length)` must be used instead;
- `copy!(dst, src)` is deprecated, you can use either `copyto!(dst, src)` or `Future.copy!(dst, src)` instead;
- `parse()` is deprecated, `Meta.parse()` must be used instead.

Thank you!

**Comment by alanderos91** [comment]
Thanks, the changes for v0.7 are on their way and I'll tag a release once the tests all pass.

**Comment by oliviaAB** [comment]
Ok, thank you!
