### ISSUE TITLE
Import warnings during BioSimulator installation

### ISSUE THREAD

**Issue by oliviaAB** [alanderos91/BioSimulator.jl#15]
Hi, 
When I'm installing BioSimulator, I get the following warnings:
```
WARNING: could not import Base.start into BioSimulator
WARNING: could not import Base.done into BioSimulator
WARNING: could not import Base.next into BioSimulator
```
This must be because the three functions have been replaced in the new iteration interface with the function `iterate()`. It does not seem to affect the simulations so far, but I guess it could be problematic in certain situations. Is it possible to remove the import to these functions to avoid the warnings?

Thanks!

**Comment by alanderos91** [comment]
Closed by #16
