### ISSUE TITLE
Very regular pattern of the variance profile

### ISSUE THREAD

**Issue by skycolt** [alanderos91/BioSimulator.jl#22]
<img width="797" alt="Screen Shot 2019-10-03 at 3 59 28 PM" src="https://user-images.githubusercontent.com/28885342/66159841-d16fee80-e5f6-11e9-8219-8356f612b2de.png">

Hello,

I am doing simulation with simple simulation and plot command.
    result = simulate(model, Direct(), time = 10000.0, epochs = 50, trials = 1000)
plot(result; plot_type = :meantrajectory)

I got the result that you can see from the attached picture. There are very regular patterns for the variance of all the variables. if you look carefully, similar pattern also exist for your example. as a stochastic simulation, I don't expect the variance to change so regularly. Do you think it a problem? Is there something I can do like to choose a better random number generator?

Thanks

**Comment by skycolt** [comment]
I get the data from result file and drew the figure myself. It now looks like this:
<img width="772" alt="Screen Shot 2019-10-03 at 5 08 49 PM" src="https://user-images.githubusercontent.com/28885342/66164460-bbffc200-e600-11e9-876b-2f5f421cb938.png">

I think you may have something wrong in your plot function, maybe on calculating the error.

**Comment by alanderos91** [comment]
I have not seriously considered whether the built-in RNG is appropriate for stochastic simulation in general. Adding other RNG types is straightforward, but I have not introduced it yet (I've been working on a rather big change offline).

That being said, I don't think the RNG is causing the regular pattern. I have come across this myself but never been able to reproduce it (but it happens often enough). I suspected it is related to the way the "regular paths" are constructed. Measurements over regular intervals are binned; see [here](https://github.com/alanderos91/BioSimulator.jl/blob/master/src/output/regular_path.jl#L22).

How did you simulate the data you plotted in your second figure? If you used the "fixed interval" option then it isolates the problem to the plotting recipe [here](https://github.com/alanderos91/BioSimulator.jl/blob/master/src/output/average_path.jl#L21).

**Comment by skycolt** [comment]
Now I don't think it's the problem of RNG but that's definitely an option great to have. I used the following code to generate the cure for one species. It looks like the problem is somewhere post simulation.

result = simulate(model, OptimizedDirect(), time = 10000.0, epochs = 200, trials = 2000)
data=result.simulation_data
for i=1:2000
       s1[i,:]=data[i].xdata[1,:]
end
plot(1:201,mean(s1,dims=1)',yerr=std(s1,dims=1)')
