### ISSUE TITLE
Citation of BioSimulator

### ISSUE THREAD

**Issue by oliviaAB** [alanderos91/BioSimulator.jl#37]
Hi, it's not an issue, but just to let you know that we published a paper to present our simulator sismonr, that relies on BioSimulator for the stochastic simulation. Thanks for your package and your help!

Olivia Angelin-Bonnet, Patrick J Biggs, Samantha Baldwin, Susan Thomson, Matthieu Vignes, sismonr: simulation of in silico multi-omic networks with adjustable ploidy and post-transcriptional regulation in R, Bioinformatics, btaa002, https://doi.org/10.1093/bioinformatics/btaa002

**Comment by alanderos91** [comment]
Appreciate the citation!
