### ISSUE TITLE
How to model reactions with complicated rate terms?

### ISSUE THREAD

**Issue by askhari139** [alanderos91/BioSimulator.jl#42]
How to simulate reactions that have complicated rate terms? For example, in a 2 reactant system (A,B), the production rate of A is p*(B^n/(K^n + B^n)) where p,n, and K are constants.

**Comment by alanderos91** [comment]
This is not currently supported in BioSimulator. It is possible, but requires some work. If you're interested in giving this a try, I can walk you through what needs to be done. Unfortunately, it is unlikely that I will get to this any time soon.

Alternatively, you might give [Catalyst.jl](https://github.com/SciML/Catalyst.jl) or [Gillespie.jl](https://github.com/sdwfrost/Gillespie.jl) a try. Both packages are excellent and support more general rate functions.

Edit: I realized the Catalyst.jl docs are quite vast. See [this](https://catalyst.sciml.ai/stable/tutorials/models/#Stochastic-simulations-using-discrete-stochastic-simulation-algorithms) and [this](https://catalyst.sciml.ai/stable/tutorials/advanced/#User-defined-functions-in-reaction-rates) in the Catalyst.jl documentation for what you need.

**Comment by askhari139** [comment]
@alanderos91 Thank you very much for the Catalyst.jl links! That is exactly what I needed.
