### ISSUE TITLE
benchmark code?

### ISSUE THREAD

**Issue by klkeys** [alanderos91/BioSimulator.jl#9]
Now that the manuscript is out (see [here](https://www.sciencedirect.com/science/article/pii/S0169260718301822?dgcid=coauthor) ) the benchmarks should be public. Is that code available?

**Comment by alanderos91** [comment]
Waiting on #11.

I'd like to get the StochPy benchmarks to use BenchmarkTools.jl in the future...

**Comment by klkeys** [comment]
Status of #11?

**Comment by alanderos91** [comment]
The branch was merged and is in master.
